### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by ghost** [The-Yerbas-Endeavor/yerbas#28]
![image](https://github.com/The-Yerbas-Endeavor/yerbas/assets/117243445/e64d890c-8fac-4a7f-bae4-63b3f520d4a0)

I am attempting to build yerbas from source on ubuntu 18 with the following command

```
sudo apt update && sudo apt upgrade &&
git clone https://github.com/The-Yerbas-Endeavor/yerbas/ --depth 1 &&
cd yerbas/depends/ &&
chmod +x conf* &&
make -j2 &&
cd .. &&
find -iname '*.sh'|xargs chmod +x &&
chmod +x src/leveldb/build_detect_platform &&
autoreconf -fi &&
./configure --disable-tests --disable-bench --prefix=pwd/depends/x86_64-pc-linux-gnu/ &&
make -j2
```

getting this error

Fetching protobuf-2.6.1.tar.bz2 from https://github.com/google/protobuf/releases/download/v2.6.1
/bin/sh: 1: curl: not found
Fetching protobuf-2.6.1.tar.bz2 from https://pool.nowput.org/depends/
/bin/sh: 1: curl: not found
funcs.mk:244: recipe for target '/home/yerbas/yerbas/depends/yerbas/depends/sources/download-stamps/.stamp_fetched-native_protobuf-protobuf-2.6.1.tar.bz2.hash' failed

**Comment by The-Yerbas-Endeavor** [comment]
Is curl installed?
`apt install curl`
Do keep in mind Ubuntu 18 is no longer supported. Might still be able to build, haven't tried in awhile
